name: food_app
description: A new Flutter project

publish_to: 'none' # يمنع النشر إلى pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_staggered_grid_view: ^0.6.1
  responsive_builder: ^0.5.0

  # إدارة الحالة بين الودجات
  provider: ^6.0.5

  # شريط التنقل السفلي
  convex_bottom_bar: ^3.2.0

  # إدارة أحجام الشاشة
  flutter_screenutil: ^5.8.4

  # قواعد البيانات المحلية
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # ميزات إضافية
  url_launcher: ^6.1.9
  google_fonts: ^4.0.3
  email_validator: ^2.0.1
  image_picker: ^0.8.6+3
  shared_preferences: ^2.5.2
  flutter_animate: ^4.5.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
